### ISSUE TITLE
Wrong response when issue a cmpServlet request!

### ISSUE THREAD

**Issue by ljyxsg** [xipki/xipki#221] opened 2021-08-03 07:46 UTC
![postman](https://user-images.githubusercontent.com/88369916/127977461-956cc857-ca51-40ab-af98-49e9a1de99d0.png)
![tomcat](https://user-images.githubusercontent.com/88369916/127977466-8df02ae2-b1f7-4242-85ed-9e07d8df6239.png)

I deploy xipki on windows, then running ca_servlet and ocsp_servlet, when i issue a request, it return 500?

> http://localhost:8080/ca_servlet_war/cmp/myca

**Comment by xipki** [comment] 2021-08-05 06:24
For bug-report please upload the testdata and log files, describe the version of XiPKI, OS and JRE/JDK, and the steps to reproduce the bug.

**Comment by xipki** [comment] 2021-08-16 20:27
No update since 2 weeks. Close it first.

**Closed by xipki** 2021-08-16 20:27 UTC

**Comment by ljyxsg** [comment] 2021-09-08 07:49
I have added a CA Certificate, thanks, close it!
