### ISSUE TITLE
Facing  errror while initialising ca schema

### ISSUE THREAD

**Issue by sanjiths** [xipki/xipki#299] opened 2023-10-05 07:16 UTC
mysql backend is enabled with TLS:1.3 

Facing below errror while initialising ca schema:
karaf@root()> ca:sql --db-conf /opt/tomcat/xipki/etc/ca/database/ca-db.properties /home/causer/xipki-mgmt-cli-6.3.0/xipki/sql/ca-init.sql
[ WARN] (pipe-ca:sql --db-conf /opt/tomcat/xipki/etc/ca/database/ca-db.properties /home/causer/xipki-mgmt-cli-6.3.0/xipki/sql/ca-init.sql) useSsl option is deprecated, replaced by option sslMode
[ WARN] (pipe-ca:sql --db-conf /opt/tomcat/xipki/etc/ca/database/ca-db.properties /home/causer/xipki-mgmt-cli-6.3.0/xipki/sql/ca-init.sql) disableSslHostnameVerification option is deprecated, replaced by setting option sslMode=verify-ca
[ WARN] (pipe-ca:sql --db-conf /opt/tomcat/xipki/etc/ca/database/ca-db.properties /home/causer/xipki-mgmt-cli-6.3.0/xipki/sql/ca-init.sql) useSsl option is deprecated, replaced by option sslMode
[ WARN] (pipe-ca:sql --db-conf /opt/tomcat/xipki/etc/ca/database/ca-db.properties /home/causer/xipki-mgmt-cli-6.3.0/xipki/sql/ca-init.sql) disableSslHostnameVerification option is deprecated, replaced by setting option sslMode=verify-ca

In ca-db.properties, I have configured the datasource URL with tls options.
dataSource.url = jdbc:mariadb://zts-cmdb:3306/ca?user=ca&password=azUA5XIutZCscO1w&useSSL=true&trustStore=/home/causer/keystore&trustStorePassword=RWxPZ1B0Rm5iaVBDV3dGdw==&keyStore=/home/causer/keystore&keyStorePassword=RWxPZ1B0Rm5iaVBDV3dGdw==&enabledSslProtocolSuites=TLSv1.3&disableSslHostnameVerification=true

This was working with xipki-5.3.0v

Based on error seen, i tried using "sslMode=verify-ca" but doesnt work:
dataSource.url = jdbc:mariadb://zts-cmdb:3308/ca?user=ca&password=azUA5XIutZCscO1w&trustStore=/home/causer/keystore&trustStorePassword=RWxPZ1B0Rm5iaVBDV3dGdw==&keyStore=/home/causer/keystore&keyStorePassword=RWxPZ1B0Rm5iaVBDV3dGdw==&enabledSslProtocolSuites=TLSv1.3&sslMode=verify-ca

Could you pls share a working configuration?

**Comment by sanjiths** [comment] 2023-10-05 07:17
With new configuration shared in description, it fails with err:
karaf@root()> ca:sql --db-conf /opt/tomcat/xipki/etc/ca/database/ca-db.properties /home/causer/xipki-mgmt-cli-6.3.0/xipki/sql/ca-init.sql
Error executing command: Failed to initialize pool: (conn=82) Could not connect to zts-cmdb:3308 : PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target

**Comment by xipki** [comment] 2023-10-05 20:40
This is an issue related to the mariadb database. The different behaviors may be caused by different versions of mariadb-jdbc-client.

This link helps you understanding the cause: https://blog.packagecloud.io/solve-unable-to-find-valid-certification-path-to-requested-target/

**Comment by xipki** [comment] 2023-11-21 20:39
Any update?

**Comment by sanjiths** [comment] 2023-11-23 10:05
I am currently trying to install xipki 6.5.0 snapshot version with non-tls mode. Let me try with TLS once this is successful

**Comment by xipki** [comment] 2023-12-16 22:38
Close this issue since it is mysql problem.

**Closed by xipki** 2023-12-16 22:38 UTC
